version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_local
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container_local
  #   restart: always
  #   ports:
  #     - 5050:5050
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin
