# Alias define
alias lofi="tizonia --youtube-audio-mix https://www.youtube.com/watch\?v\=bebuiaSKtU4"
alias falloutboy="tizonia --youtube-audio-mix https://www.youtube.com/watch\?v\=LBr7kECsjcQ\&list\=OLAK5uy_ltl03A3bXBWEfk1Weu5PgBD1Hs_VJkWas"
alias cl="clear"
alias ex="exit"
alias update-all="sudo apt -y update && sudo apt -y upgrade && sudo apt -y  autoclean && sudo apt -y autoremove"
alias standardlog="standard --fix | snazzy"
alias npmplease="rm -rf node_modules && rm package-lock.json && npm install"
alias rl=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias pl="php -S localhost:8886"
alias pf="prettier ./*.php --write"
alias hc="history -c"
alias cat="bat"
alias ktmux="tmux kill-server"

