# Alias define
alias lofi="tizonia --youtube-audio-mix https://www.youtube.com/watch\?v\=bebuiaSKtU4"
alias falloutboy="tizonia --youtube-audio-mix https://www.youtube.com/watch\?v\=LBr7kECsjcQ\&list\=OLAK5uy_ltl03A3bXBWEfk1Weu5PgBD1Hs_VJkWas"
alias nujabes="tizonia --youtube-audio-playlist https://www.youtube.com/watch\?v\=_qU2MXeAz1E\&list\=PLpleWfPiCfvaeKJdaieurunjfUc9NpjDE\&index\=3"
alias cl="clear"
alias ex="exit"
alias update-all="sudo apt -y update && sudo apt -y upgrade && sudo apt -y  autoclean && sudo apt -y autoremove"
alias standardlog="standard --fix | snazzy"
alias npmplease="rm -rf node_modules && rm package-lock.json && npm install"
alias rl=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias pl="php -S localhost:8888"
alias pf="prettier ./*.php --write"
alias hc="history -c"
alias ktmux="tmux kill-server"
alias bs="browser-sync start --server --files '*' --port "

