# Don't print a new line at the start of the prompt
add_newline = true

[character]
symbol = ">"

[php]
symbol = "php "

[java]
symbol = "java "

[nodejs]
symbol = "nodejs "

[python]
symbol = "python "

[ruby]
symbol = "ruby "

[rust]
symbol = "rust "

[aws]
symbol = "aws "

[dotnet]
symbol = "dotnet "

[conda]
symbol = "conda "

[package]
symbol = "package "
