[colors.bright]
black = "#555753"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.normal]
black = "#2e3436"
blue = "#3465a4"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#d7af00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
cursor = "#00ff00"
text = "#000000"

[cursor.style]
shape = "Block"

[font]
size = 10

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "none"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "none"
key = "Space"
mode = "Vi|~Search"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "none"
key = "B"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
opacity = 1.0
startup_mode = "Maximized"
title = "Alacritty"
